language: python

matrix:
  include:
    - python: "3.7"  # remove workaround if travis releases 3.7 officially
      env: PY_VERSION=py37
      dist: xenial
      sudo: true
    - python: "3.8-dev"
      env: PY_VERSION=py38
  allow_failures:
    - python: "3.8-dev"

addons:
  apt:
    update: true

install:
  - pip install --upgrade -e .[dev]
  - pip install codacy-coverage codecov

script:
  - ./scripts/build.sh "$PY_VERSION"
  - pytest -v --cov-config=.coveragerc --cov=cmt --cov-report=xml
  - python setup.py check -v -m -s
  - twine check dist/*
  - sphinx-build -b html ./doc/source/ ./build/doc/html/
  - sphinx-build -b linkcheck ./doc/source/ ./build/doc/linkcheck/

after_success:
  - codecov
  - python-codacy-coverage -r coverage.xml

deploy:
  - provider: script
    skip_cleanup: true
    script: twine upload -u $PYPI_USER -p $PYPI_PASSWORD --skip-existing dist/*
    on:
      branch: master
      repo: IceflowRE/cmt
      tags: true
